#!/bin/bash
# Insert the state for images to pdf dialog
sed -i 's/    var showTextToPdfDialog by remember { mutableStateOf(false) }/    var showTextToPdfDialog by remember { mutableStateOf(false) }\n    var showImagesToPdfDialog by remember { mutableStateOf(false) }\n    var selectedImagesForPdf by remember { mutableStateOf<List<android.net.Uri>>(emptyList()) }/g' app/src/main/java/com/silentpdf/app/ui/screens/LibraryScreen.kt

# Replace the image picker launcher logic
perl -0777 -pi -e 's/    val imagePickerLauncher = rememberLauncherForActivityResult\(\s*contract = ActivityResultContracts\.GetMultipleContents\(\),\s*onResult = \{ uris ->\s*if \(uris\.isNotEmpty\(\)\) \{\s*kotlinx\.coroutines\.CoroutineScope\(kotlinx\.coroutines\.Dispatchers\.IO\)\.launch \{\s*val pdfUri = com\.silentpdf\.app\.util\.PdfCreator\.createImagesPdf\(context, uris, "Scanned_\\\$\{System\.currentTimeMillis\(\)\}"\)\s*if \(pdfUri != null\) \{\s*kotlinx\.coroutines\.withContext\(kotlinx\.coroutines\.Dispatchers\.Main\) \{\s*android\.widget\.Toast\.makeText\(context, "PDF created successfully!", android\.widget\.Toast\.LENGTH_SHORT\)\.show\(\)\s*val file = java\.io\.File\(pdfUri\.path!!\)\s*viewModel\.importPdf\(pdfUri, file\.name, file\.length\(\)\)\s*\}\s*\}\s*\}\s*\}\s*\}\s*\)/    val imagePickerLauncher = rememberLauncherForActivityResult(\n        contract = ActivityResultContracts.GetMultipleContents(),\n        onResult = { uris ->\n            if (uris.isNotEmpty()) {\n                selectedImagesForPdf = uris\n                showImagesToPdfDialog = true\n            }\n        }\n    )/g' app/src/main/java/com/silentpdf/app/ui/screens/LibraryScreen.kt

# Inject ImagesToPdfDialog call
perl -0777 -pi -e 's/    if \(showTextToPdfDialog\) \{/    if (showImagesToPdfDialog) {\n        ImagesToPdfDialog(\n            imageUris = selectedImagesForPdf,\n            onDismiss = { showImagesToPdfDialog = false },\n            onPdfCreated = { uri ->\n                val file = java.io.File(uri.path!!)\n                viewModel.importPdf(uri, file.name, file.length())\n            }\n        )\n    }\n\n    if (showTextToPdfDialog) {/g' app/src/main/java/com/silentpdf/app/ui/screens/LibraryScreen.kt
