import os

replacements_reader = [
    ('Bogga ${note.pageNumber + 1}', 'Page ${note.pageNumber + 1}'),
    ('contentDescription = "Tirtir"', 'contentDescription = "Delete"'),
    ('Fadlan oggolow fasaxa Microphone-ka si aad cod u duubto.', 'Please grant Microphone permission to record audio.'),
    ('Text("Ka laabo")', 'Text("Cancel")'),
    ('contentDescription = "Ka laabo"', 'contentDescription = "Cancel"'),
    ('Faylkaan waa la xidhay', 'This file is locked'),
    ('Fadlan geli password-ka saxda ah si aad u furto dukumentigan.', 'Please enter the correct password to open this document.'),
    ('Geli password-ka...', 'Enter password...'),
    ('Fura Dukumentiga', 'Open Document'),
    ('Hagaha Buugga', 'Book Outline'),
    ('Raadi', 'Search'),
    ('Ma jiraan qoraallo (notes) aad ku dartay buuggan.', 'No notes added to this book.'),
    ('Ma jiraan cutubyo la helay', 'No chapters found'),
    ('Ma jiraan bogag aad calaamadsatay dhowaan.', 'No recently bookmarked pages.'),
    ('Bogga ${bookmark.pageNumber + 1}', 'Page ${bookmark.pageNumber + 1}'),
    ('Eray ku raadi buugga...', 'Search word in book...'),
    ('contentDescription = "Eber"', 'contentDescription = "Clear"'),
    ('Ku qor eray barta sare si aad uga raadiso dhammaan boggaga buugga.', 'Type a word above to search across all pages.'),
    ('Wax natiijo ah lama helin.', 'No results found.'),
    ('La helay ${searchInPdfResults.size} meelood', 'Found in ${searchInPdfResults.size} places'),
    ('Bogga ${result.pageNumber + 1}', 'Page ${result.pageNumber + 1}'),
    ('${result.occurrencesCount} jeer', '${result.occurrencesCount} times'),
    ('Ku dhex raadi erayo', 'Search text'),
    ('Sawir / Qor', 'Draw / Write'),
    ('Madow / Caddaan', 'Black / White'),
    ('Bookmark', 'Bookmark'),
    ('Dheeraad', 'More'),
    ('Ku dar/Beddel Qoraal (Note)', 'Add/Edit Note'),
    ('Toos u weyneey (Fullscreen)', 'Fullscreen'),
    ('Daabac (Print)', 'Print'),
    ('Faahfaahin (Details)', 'Details'),
    ('Duub Cod (Voice Note)', 'Voice Note'),
    ('Qalin', 'Pen'),
    ('Tirtire', 'Eraser'),
    ('Ka laabo qoraalka', 'Undo drawing'),
    ('Xajmiga', 'Size'),
    ('U gudub boggii hore', 'Go to previous page'),
    ('Bogga ${currentPage + 1} ee $pageCount', 'Page ${currentPage + 1} of $pageCount'),
    ('U bood Bog', 'Jump to Page'),
    ('Ku qor lambarka bogga aad rabto inaad u booddo (1 ilaa $pageCount):', 'Enter the page number to jump to (1 to $pageCount):'),
    ('Nambarka Bogga', 'Page Number'),
    ('Haa', 'Yes'),
    ('U gudub boga xiga', 'Go to next page'),
    ('Faahfaahinta Buugga', 'Book Details'),
    ('Magaca:', 'Name:'),
    ('Mugga:', 'Size:'),
    ('Bogagga:', 'Pages:'),
    ('Waa la soo raryaa...', 'Loading...'),
    ('Xidh', 'Close'),
    ('Bogga PDF', 'PDF Page'),
    ('Qoraal Bogga', 'Page Note'),
    ('Ma aanan rari karin boggan', 'Could not load this page'),
    ('Qoraalka Bogga ${currentPage + 1}', 'Note for Page ${currentPage + 1}'),
    ('Qoraalkaaga', 'Your Note'),
    ('Halkan ku qor qoraal gaar ah...', 'Write a specific note here...'),
    ('Text("Kaydi")', 'Text("Save")'),
    ('Text("Tirtir")', 'Text("Delete")'),
    ('Duubista Codka - Bogga ${currentPage + 1}', 'Voice Note - Page ${currentPage + 1}'),
    ('Codkaaga ayaa hadda la duubayaa...', 'Recording your voice now...'),
    ('contentDescription = "Jooji"', 'contentDescription = "Stop"'),
    ('Dhegeyso & Keydi', 'Listen & Save'),
    ('Boggan wuxuu horey u leeyahay cod duuban:', 'This page already has a voice note:'),
    ('Ma rabtaa inaad dib u duubto codka?', 'Do you want to record again?'),
    ('Riix badhanka hoose si aad u bilowdo duubista codka.', 'Press the button below to start recording voice.'),
    ('Duub Cod Cusub', 'Record New Voice Note'),
    ('Bilow Duubista', 'Start Recording'),
    ('Garaac / Hakaji', 'Play / Pause'),
    ('Codka Bogga', 'Page Voice Note'),
    ('Folder:', 'Category:')
]

replacements_library = [
    ('Raadi magaca buugga...', 'Search book name...'),
    ('Dhammaan', 'All'),
    ('Kuwa dhow', 'Recent'),
    ('Kuwa aad jeceshahay', 'Favorites'),
    ('Lama helin buug la magac ah', 'No book found with this name'),
    ('Ma jiraan buugaag PDF ah', 'No PDF books'),
    ('Fadlan isku day inaad raadiso eray kale.', 'Please try searching another word.'),
    ('Guji batoonka hoose si aad u soo dhoweyso buug maxalli ah.', 'Click the button below to import a local book.'),
    ('Kuwii ugu dambeeyay', 'Recently viewed'),
    ('${recentPdfs.size} buug', '${recentPdfs.size} books'),
    ('Folders / Qaybaha', 'Folders / Categories'),
    ('Folder Cusub', 'New Folder'),
    ('Buugaagta ku dhex jira: $selectedCategory', 'Books in: $selectedCategory'),
    ('Dhammaan Buugaagta', 'All Books'),
    ('Abuur Folder Cusub', 'Create New Folder'),
    ('Ku qor magaca folder-ka aad rabto inaad abuurto si aad u kala nidaamiso buugaagtaada.', 'Enter the name of the folder you want to create to organize your books.'),
    ('Tusaale: Buugaagta Taariikhda', 'Example: History Books'),
    ('Text("Abuur")', 'Text("Create")'),
    ('Text("Ka laabo")', 'Text("Cancel")'),
    ('U rar Folder kale', 'Move to Folder'),
    ("Dooro folder-ka aad rabto inaad u rarto '${pdf.fileName}':", "Select the folder you want to move '${pdf.fileName}' to:"),
    ('Folder dibadda ah (Default)', 'Default Folder'),
    ('Ama u samee folder cusub:', 'Or create a new folder:'),
    ('Ku qor magac cusub...', 'Enter new name...'),
    ('Text("Xaqiiji")', 'Text("Confirm")'),
    ('Kala Hormari Buugaagta', 'Sort Books'),
    ('A-Z (Magac)', 'A-Z (Name)'),
    ('Xilligii dhowaa (Taariikh)', 'Recent (Date)'),
    ('Mugga buugga (Xajmi)', 'Book Size'),
    ('Text("Xidh")', 'Text("Close")'),
    ('Bogga ${lastPage + 1} ee $total', 'Page ${lastPage + 1} of $total'),
    ('Bog dhowaan', 'Recent page'),
    ('Ku rar Folder', 'Move to Folder'),
    ('La wadaag (Share)', 'Share'),
    ('Tirtir (Delete)', 'Delete'),
    ('Amniga App-ka', 'App Security'),
    ('Samee PIN-ka', 'Set PIN'),
    ('Xaqiiji PIN-ka', 'Confirm PIN'),
    ('Geli PIN-ka hadda', 'Enter PIN'),
    ('PIN-ka App-ka hadda waa uu shaqeynayaa. Dukumentiyadaada waa ay badbaadsan yihiin.', 'App PIN is currently active. Your documents are safe.'),
    ('Geli PIN-ka si aad u damiso', 'Enter PIN to disable'),
    ('4 lambar', '4 digits'),
    ('Fadlan geli 4-digit PIN aad ku xireyso app-ka.', 'Please enter a 4-digit PIN to lock the app.'),
    ('PIN Cusub', 'New PIN'),
    ('Ku celi PIN-ka hadda aad qortay si aad u xaqiijiso.', 'Repeat the PIN you just entered to confirm.'),
    ('Xaqiiji PIN', 'Confirm PIN'),
    ('PIN-ka aad gelisay waa khalad!', 'The PIN you entered is incorrect!'),
    ('Fadlan qor 4 lambar.', 'Please enter 4 digits.'),
    ('PIN-nada aad qortay isku mid ma aha!', 'The PINs you entered do not match!'),
    ('Text("Dami")', 'Text("Disable")'),
    ('Text("Sii soco")', 'Text("Continue")'),
    ('Text("Kaydi")', 'Text("Save")')
]

def apply_replacements(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w') as f:
        f.write(content)

apply_replacements('app/src/main/java/com/example/ui/screens/ReaderScreen.kt', replacements_reader)
apply_replacements('app/src/main/java/com/example/ui/screens/LibraryScreen.kt', replacements_library)

print("Translations applied.")
